// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAfk_7aWO6350vIXzUKoropGguhoYmdAAQ',
    appId: '1:8525069954:web:0ed721307ee461dabebe9b',
    messagingSenderId: '8525069954',
    projectId: 'fstore-46707',
    authDomain: 'fstore-46707.firebaseapp.com',
    storageBucket: 'fstore-46707.appspot.com',
    measurementId: 'G-J486HJNYZQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBTBm_TOEfEzRiBrFNuUC3pLGc5MKFZAc8',
    appId: '1:8525069954:android:ff73e19a6898c66bbebe9b',
    messagingSenderId: '8525069954',
    projectId: 'fstore-46707',
    storageBucket: 'fstore-46707.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC3JKkUk0a7ZnXYmy_osbLyIGnfGkFjiwI',
    appId: '1:8525069954:ios:1c721cf5c2e41f16bebe9b',
    messagingSenderId: '8525069954',
    projectId: 'fstore-46707',
    storageBucket: 'fstore-46707.appspot.com',
    androidClientId: '8525069954-tac1g0rd6em8kth0bl67klt2od0bd390.apps.googleusercontent.com',
    iosClientId: '8525069954-tcrq007lq4etijika76t9mq510tv75pi.apps.googleusercontent.com',
    iosBundleId: 'com.example.fStoreDashboard',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAfk_7aWO6350vIXzUKoropGguhoYmdAAQ',
    appId: '1:8525069954:web:40a765a82df1a9c2bebe9b',
    messagingSenderId: '8525069954',
    projectId: 'fstore-46707',
    authDomain: 'fstore-46707.firebaseapp.com',
    storageBucket: 'fstore-46707.appspot.com',
    measurementId: 'G-BFBQ7RVQR0',
  );

}